#pragma once
enum class MessageType
{
	M_GOT_REQ,
	MTS_ASK_FOR_IMAGES,
	STM_SEND_IMAGES_PROP,
	MTS_GIVE_THE_CHOSEN_IMAGE,
	STM_RESPONSE_TO_THE_CHOSEN_IMAGE,
	MTS_REQ_FOR_PHOTO,
	MTIP_REQ_FOR_REAL_MAP,
	MTM_NO_COMMUNICATION_AT_ALL,
	MTM_SLAVES_NOT_COMMUNICATE,
	//IPTM_SEND_THE_IMAGES,
	MTS_SEND_LOCATION,
	MTS_MOVE_OUT_OF_THIS_EREA,
	MTS_STOP_SEND_LOCATION,
	STM_LOCATION,
	MTS_STOP_AT_PLACE,
	MTS_BACK_TO_STARTING_POINT,
	MTS_SEND_EVENTS,
	STM_GET_EVENTS,
	size
};


