#pragma once
enum class MessageType
{
	MtoS,
	StoM,
	M_GOT_REQ,
	STM_SEND_IMAGES_PROP,
	MTS_SEND_LOCATION,
	MTS_MOVE,
	MTS_STOP_SEND_LOCATION,
	MTS_STOP_AT_PLACE,
	MTS_BACK,
	MTS_SEND_EVENTS,
	STM_GET_EVENTS,
	OTM_SEND_SORTED_EVENT_LIST,
	MTO_GET_SORTED_EVENT_LIST
};

